# Generated by Django 6.1.1 on 2026-09-19 13:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'full_name',
                    models.CharField(max_length=200, verbose_name='نام گیرنده'),
                ),
                ('phone', models.CharField(max_length=20, verbose_name='تلفن')),
                ('address', models.TextField(verbose_name='آدرس')),
                (
                    'total_amount',
                    models.PositiveIntegerField(
                        default=0, verbose_name='مبلغ کل (تومان)'
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending_payment', 'در انتظار پرداخت'),
                            ('paid', 'پرداخت\u200cشده'),
                            ('failed', 'ناموفق'),
                            ('cancelled', 'لغو\u200cشده'),
                            ('fulfilled', 'ارسال\u200cشده'),
                        ],
                        db_index=True,
                        default='pending_payment',
                        max_length=32,
                        verbose_name='وضعیت',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='orders',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='کاربر',
                    ),
                ),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'variant_id_snapshot',
                    models.PositiveIntegerField(
                        blank=True,
                        help_text='برای کسر موجودی پس از پرداخت',
                        null=True,
                        verbose_name='واریانت',
                    ),
                ),
                (
                    'product_name',
                    models.CharField(max_length=200, verbose_name='نام محصول'),
                ),
                (
                    'size',
                    models.CharField(blank=True, max_length=80, verbose_name='سایز'),
                ),
                (
                    'color_name',
                    models.CharField(blank=True, max_length=80, verbose_name='رنگ'),
                ),
                (
                    'unit_price',
                    models.PositiveIntegerField(verbose_name='قیمت واحد (تومان)'),
                ),
                (
                    'quantity',
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name='تعداد',
                    ),
                ),
                (
                    'line_total',
                    models.PositiveIntegerField(verbose_name='جمع ردیف (تومان)'),
                ),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='orders.order',
                        verbose_name='سفارش',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='order_items',
                        to='catalog.product',
                        verbose_name='محصول',
                    ),
                ),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
    ]
