services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: fitile
      POSTGRES_USER: fitile
      POSTGRES_PASSWORD: fitile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fitile -d fitile"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  web:
    build: .
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.production
      DJANGO_DEBUG: "false"
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-docker-dev-change-me-please-use-long-secret}
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,web
      DJANGO_SITE_NAME: فیتیله شاپ
      DJANGO_LANGUAGE_CODE: fa
      DJANGO_TEXT_DIRECTION: rtl
      DJANGO_TIME_ZONE: Asia/Tehran
      DATABASE_URL: postgres://fitile:fitile@db:5432/fitile
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      ZARINPAL_CALLBACK_URL: http://localhost:8000/shop/payment/callback/
    ports:
      - "8000:8000"
    volumes:
      - media_data:/app/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build: .
    command: celery -A core worker -l info
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.production
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-docker-dev-change-me-please-use-long-secret}
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,web
      DATABASE_URL: postgres://fitile:fitile@db:5432/fitile
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      web:
        condition: service_started

volumes:
  postgres_data:
  media_data:
