# Generated by Django 6.1.1 on 2026-09-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                (
                    'email',
                    models.EmailField(blank=True, max_length=254, verbose_name='ایمیل'),
                ),
                (
                    'service_interest',
                    models.CharField(
                        blank=True, max_length=150, verbose_name='موضوع / نوع تابلو'
                    ),
                ),
                ('message', models.TextField(verbose_name='پیام')),
                (
                    'is_read',
                    models.BooleanField(default=False, verbose_name='خوانده شده'),
                ),
            ],
            options={
                'verbose_name': 'درخواست مشاوره',
                'verbose_name_plural': 'درخواست\u200cهای مشاوره',
                'ordering': ['-created_at'],
            },
        ),
    ]
