# Generated by Django 6.1.1 on 2026-09-19 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                (
                    'slug',
                    models.SlugField(
                        allow_unicode=True,
                        max_length=220,
                        unique=True,
                        verbose_name='اسلاگ',
                    ),
                ),
                (
                    'excerpt',
                    models.CharField(blank=True, max_length=300, verbose_name='خلاصه'),
                ),
                ('body', models.TextField(verbose_name='متن')),
                (
                    'cover',
                    models.ImageField(
                        blank=True, upload_to='blog/covers/', verbose_name='تصویر شاخص'
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(default=False, verbose_name='منتشر شده'),
                ),
                (
                    'published_at',
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name='زمان انتشار'
                    ),
                ),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقاله\u200cها',
                'ordering': ['-published_at'],
            },
        ),
    ]
