# Generated by Django 6.1.1 on 2026-09-19 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'authority',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name='Authority',
                    ),
                ),
                (
                    'ref_id',
                    models.CharField(
                        blank=True, max_length=64, verbose_name='کد پیگیری'
                    ),
                ),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('initiated', 'آغاز\u200cشده'),
                            ('redirected', 'هدایت\u200cشده'),
                            ('verified', 'تأیید\u200cشده'),
                            ('failed', 'ناموفق'),
                        ],
                        db_index=True,
                        default='initiated',
                        max_length=32,
                        verbose_name='وضعیت',
                    ),
                ),
                (
                    'raw_response',
                    models.JSONField(
                        blank=True, default=dict, verbose_name='پاسخ درگاه'
                    ),
                ),
                (
                    'stock_decremented',
                    models.BooleanField(default=False, verbose_name='موجودی کسر شده'),
                ),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='payments',
                        to='orders.order',
                        verbose_name='سفارش',
                    ),
                ),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ('-created_at',),
            },
        ),
    ]
