# Generated by Django 6.1.1 on 2026-09-19 11:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                (
                    'slug',
                    models.SlugField(
                        allow_unicode=True,
                        max_length=140,
                        unique=True,
                        verbose_name='اسلاگ',
                    ),
                ),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته\u200cها',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'full_name',
                    models.CharField(max_length=200, verbose_name='نام گیرنده'),
                ),
                ('phone', models.CharField(max_length=20, verbose_name='تلفن')),
                ('address', models.TextField(verbose_name='آدرس')),
                (
                    'total_amount',
                    models.PositiveIntegerField(
                        default=0, verbose_name='مبلغ کل (ریال)'
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending_payment', 'در انتظار پرداخت'),
                            ('paid', 'پرداخت\u200cشده'),
                            ('failed', 'ناموفق'),
                            ('cancelled', 'لغو\u200cشده'),
                            ('fulfilled', 'ارسال\u200cشده'),
                        ],
                        db_index=True,
                        default='pending_payment',
                        max_length=32,
                        verbose_name='وضعیت',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='orders',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='کاربر',
                    ),
                ),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'authority',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name='Authority',
                    ),
                ),
                (
                    'ref_id',
                    models.CharField(
                        blank=True, max_length=64, verbose_name='کد پیگیری'
                    ),
                ),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('initiated', 'آغاز\u200cشده'),
                            ('redirected', 'هدایت\u200cشده'),
                            ('verified', 'تأیید\u200cشده'),
                            ('failed', 'ناموفق'),
                        ],
                        db_index=True,
                        default='initiated',
                        max_length=32,
                        verbose_name='وضعیت',
                    ),
                ),
                (
                    'raw_response',
                    models.JSONField(
                        blank=True, default=dict, verbose_name='پاسخ درگاه'
                    ),
                ),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='payments',
                        to='shop.order',
                        verbose_name='سفارش',
                    ),
                ),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                (
                    'slug',
                    models.SlugField(
                        allow_unicode=True,
                        max_length=220,
                        unique=True,
                        verbose_name='اسلاگ',
                    ),
                ),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                (
                    'price',
                    models.PositiveIntegerField(
                        help_text='مبلغ به ریال',
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name='قیمت (ریال)',
                    ),
                ),
                (
                    'stock',
                    models.PositiveIntegerField(default=0, verbose_name='موجودی'),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True, upload_to='products/', verbose_name='تصویر'
                    ),
                ),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='products',
                        to='shop.category',
                        verbose_name='دسته',
                    ),
                ),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'product_name',
                    models.CharField(max_length=200, verbose_name='نام محصول'),
                ),
                ('unit_price', models.PositiveIntegerField(verbose_name='قیمت واحد')),
                (
                    'quantity',
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name='تعداد',
                    ),
                ),
                ('line_total', models.PositiveIntegerField(verbose_name='جمع ردیف')),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='shop.order',
                        verbose_name='سفارش',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='order_items',
                        to='shop.product',
                        verbose_name='محصول',
                    ),
                ),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
    ]
