# Generated by Django 6.1.1 on 2026-09-19 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.PositiveIntegerField(
                default=0, verbose_name='مبلغ کل (تومان)'
            ),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='line_total',
            field=models.PositiveIntegerField(verbose_name='جمع ردیف (تومان)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.PositiveIntegerField(verbose_name='قیمت واحد (تومان)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='مبلغ (تومان)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(
                help_text='مبلغ به تومان',
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name='قیمت (تومان)',
            ),
        ),
    ]
