# Generated by Django 6.1.1 on 2026-09-19 13:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                (
                    'slug',
                    models.SlugField(
                        allow_unicode=True,
                        max_length=140,
                        unique=True,
                        verbose_name='اسلاگ',
                    ),
                ),
                (
                    'subtitle',
                    models.CharField(
                        blank=True, max_length=200, verbose_name='زیرعنوان'
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True, upload_to='categories/', verbose_name='تصویر'
                    ),
                ),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                (
                    'sort_order',
                    models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
                ),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته\u200cها',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                (
                    'slug',
                    models.SlugField(
                        allow_unicode=True,
                        max_length=140,
                        unique=True,
                        verbose_name='اسلاگ',
                    ),
                ),
                (
                    'subtitle',
                    models.CharField(
                        blank=True, max_length=200, verbose_name='زیرعنوان'
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True, upload_to='collections/', verbose_name='تصویر'
                    ),
                ),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کالکشن',
                'verbose_name_plural': 'کالکشن\u200cها',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'badge',
                    models.CharField(blank=True, max_length=80, verbose_name='نشان'),
                ),
                ('headline', models.CharField(max_length=200, verbose_name='عنوان')),
                (
                    'headline_accent',
                    models.CharField(
                        blank=True, max_length=120, verbose_name='تأکید عنوان'
                    ),
                ),
                (
                    'subtitle',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='زیرعنوان'
                    ),
                ),
                (
                    'cta_label',
                    models.CharField(
                        default='مشاهده محصولات', max_length=80, verbose_name='متن دکمه'
                    ),
                ),
                (
                    'cta_url',
                    models.CharField(
                        default='/shop/products/',
                        max_length=200,
                        verbose_name='لینک دکمه',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True, upload_to='home/hero/', verbose_name='تصویر'
                    ),
                ),
                (
                    'theme',
                    models.CharField(
                        choices=[('dark', 'تیره'), ('light', 'روشن'), ('photo', 'عکس')],
                        default='light',
                        max_length=16,
                        verbose_name='تم',
                    ),
                ),
                (
                    'sort_order',
                    models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
                ),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'اسلاید هیرو',
                'verbose_name_plural': 'اسلایدهای هیرو',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SiteFeature',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                (
                    'subtitle',
                    models.CharField(
                        blank=True, max_length=200, verbose_name='زیرعنوان'
                    ),
                ),
                (
                    'sort_order',
                    models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
                ),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'ویژگی سایت',
                'verbose_name_plural': 'ویژگی\u200cهای سایت',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='نام')),
                ('text', models.TextField(verbose_name='متن')),
                (
                    'rating',
                    models.PositiveSmallIntegerField(default=5, verbose_name='امتیاز'),
                ),
                (
                    'initials',
                    models.CharField(blank=True, max_length=4, verbose_name='حروف'),
                ),
                (
                    'sort_order',
                    models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
                ),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نظر مشتری',
                'verbose_name_plural': 'نظرات مشتری',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                (
                    'slug',
                    models.SlugField(
                        allow_unicode=True,
                        max_length=220,
                        unique=True,
                        verbose_name='اسلاگ',
                    ),
                ),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                (
                    'price',
                    models.PositiveIntegerField(
                        help_text='قیمت پایه؛ واریانت می\u200cتواند override کند',
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name='قیمت (تومان)',
                    ),
                ),
                (
                    'sale_price',
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name='قیمت تخفیف (تومان)',
                    ),
                ),
                (
                    'stock',
                    models.PositiveIntegerField(
                        default=0,
                        help_text='اگر واریانت نباشد از این استفاده می\u200cشود',
                        verbose_name='موجودی پایه',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True, upload_to='products/', verbose_name='تصویر اصلی'
                    ),
                ),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_new', models.BooleanField(default=False, verbose_name='جدید')),
                ('is_sale', models.BooleanField(default=False, verbose_name='تخفیف')),
                (
                    'best_seller',
                    models.BooleanField(default=False, verbose_name='پرفروش'),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='products',
                        to='catalog.category',
                        verbose_name='دسته',
                    ),
                ),
                (
                    'collections',
                    models.ManyToManyField(
                        blank=True,
                        related_name='products',
                        to='catalog.collection',
                        verbose_name='کالکشن\u200cها',
                    ),
                ),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='نام')),
                (
                    'hex_code',
                    models.CharField(
                        default='#14110F', max_length=7, verbose_name='کد رنگ'
                    ),
                ),
                (
                    'sort_order',
                    models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='colors',
                        to='catalog.product',
                        verbose_name='محصول',
                    ),
                ),
            ],
            options={
                'verbose_name': 'رنگ محصول',
                'verbose_name_plural': 'رنگ\u200cهای محصول',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'file',
                    models.ImageField(
                        upload_to='products/gallery/', verbose_name='فایل'
                    ),
                ),
                (
                    'alt_text',
                    models.CharField(
                        blank=True, max_length=200, verbose_name='متن جایگزین'
                    ),
                ),
                (
                    'sort_order',
                    models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
                ),
                ('is_primary', models.BooleanField(default=False, verbose_name='اصلی')),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='images',
                        to='catalog.product',
                        verbose_name='محصول',
                    ),
                ),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.CharField(max_length=80, verbose_name='سایز / بسته')),
                (
                    'price',
                    models.PositiveIntegerField(
                        blank=True,
                        help_text='خالی = ارث از محصول',
                        null=True,
                        verbose_name='قیمت (تومان)',
                    ),
                ),
                (
                    'sale_price',
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name='تخفیف (تومان)'
                    ),
                ),
                (
                    'stock',
                    models.PositiveIntegerField(default=10, verbose_name='موجودی'),
                ),
                (
                    'sku',
                    models.CharField(blank=True, max_length=64, verbose_name='SKU'),
                ),
                (
                    'color',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='variants',
                        to='catalog.productcolor',
                        verbose_name='رنگ',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='variants',
                        to='catalog.product',
                        verbose_name='محصول',
                    ),
                ),
            ],
            options={
                'verbose_name': 'واریانت',
                'verbose_name_plural': 'واریانت\u200cها',
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(
                fields=['is_active', 'category'], name='catalog_pro_is_acti_1a8de5_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='catalog_pro_slug_2b1eb6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together={('product', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'size', 'color')},
        ),
    ]
