# Generated by Django 6.1.1 on 2026-09-19 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                (
                    'slug',
                    models.SlugField(
                        allow_unicode=True,
                        max_length=120,
                        unique=True,
                        verbose_name='اسلاگ',
                    ),
                ),
            ],
            options={
                'verbose_name': 'دسته نمونه کار',
                'verbose_name_plural': 'دسته\u200cهای نمونه کار',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                (
                    'slug',
                    models.SlugField(
                        allow_unicode=True,
                        max_length=220,
                        unique=True,
                        verbose_name='اسلاگ',
                    ),
                ),
                (
                    'summary',
                    models.CharField(blank=True, max_length=300, verbose_name='خلاصه'),
                ),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                (
                    'cover',
                    models.ImageField(
                        blank=True,
                        upload_to='portfolio/covers/',
                        verbose_name='تصویر شاخص',
                    ),
                ),
                (
                    'client_name',
                    models.CharField(
                        blank=True, max_length=120, verbose_name='نام مشتری'
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(default=True, verbose_name='منتشر شده'),
                ),
                (
                    'is_featured',
                    models.BooleanField(default=False, verbose_name='ویژه صفحه اصلی'),
                ),
                (
                    'category',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='projects',
                        to='portfolio.category',
                        verbose_name='دسته',
                    ),
                ),
            ],
            options={
                'verbose_name': 'نمونه کار',
                'verbose_name_plural': 'نمونه کارها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'image',
                    models.ImageField(
                        upload_to='portfolio/gallery/', verbose_name='تصویر'
                    ),
                ),
                (
                    'alt_text',
                    models.CharField(
                        blank=True, max_length=200, verbose_name='متن جایگزین'
                    ),
                ),
                (
                    'sort_order',
                    models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب'),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='images',
                        to='portfolio.project',
                        verbose_name='پروژه',
                    ),
                ),
            ],
            options={
                'verbose_name': 'تصویر نمونه کار',
                'verbose_name_plural': 'تصاویر نمونه کار',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
